server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: vu4wj/35/3ck6
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate.format_sql: true
